package modelo;
// Generated 2/10/2020 08:48:06 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DosisAplicada generated by hbm2java
 */
@Entity
@Table(name = "dosis_aplicada")
public class DosisAplicada implements java.io.Serializable {

    @Id
    @Column(name = "id_dosis_aplicada")
    private int idDosisAplicada;
    
    @JoinColumn(name = "id_dosis", nullable = false)
    @ManyToOne(optional = false, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Dosis dosis;
    
    @JoinColumn(name = "id_historial", nullable = false)
    @ManyToOne(optional = false, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Historial historial;
    
    @Column(name = "fecha_aplicacion")
    private Date fechaAplicacion;

    public DosisAplicada() {
    }

    public DosisAplicada(int idDosisAplicada, Dosis dosis, Historial historial, Date fechaAplicacion) {
        this.idDosisAplicada = idDosisAplicada;
        this.dosis = dosis;
        this.historial = historial;
        this.fechaAplicacion = fechaAplicacion;
    }

    public DosisAplicada(int idDosisAplicada, Date fechaAplicacion) {
        this.idDosisAplicada = idDosisAplicada;
        this.fechaAplicacion = fechaAplicacion;
    }

    public DosisAplicada(int idDosisAplicada, Dosis dosis, Date fechaAplicacion) {
        this.idDosisAplicada = idDosisAplicada;
        this.dosis = dosis;
        this.fechaAplicacion = fechaAplicacion;
    }

    
    public int getIdDosisAplicada() {
        return this.idDosisAplicada;
    }

    public void setIdDosisAplicada(int idDosisAplicada) {
        this.idDosisAplicada = idDosisAplicada;
    }

    public Dosis getDosis() {
        return this.dosis;
    }

    public void setDosis(Dosis dosis) {
        this.dosis = dosis;
    }

    public Historial getHistorial() {
        return this.historial;
    }

    public void setHistorial(Historial historial) {
        this.historial = historial;
    }

    public Date getFechaAplicacion() {
        return this.fechaAplicacion;
    }

    public void setFechaAplicacion(Date fechaAplicacion) {
        this.fechaAplicacion = fechaAplicacion;
    }

}
