package modelo;
// Generated 26/09/2020 10:45:07 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dosis generated by hbm2java
 */
@Entity
@Table(name = "dosis")
public class Dosis implements java.io.Serializable {

    @Id
    @Column(name = "id")
    private int id;
    @JoinColumn(name = "id_vacuna", nullable = false)
    @ManyToOne(optional = false, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Vacuna vacuna;
    @Column(name = "valor_tiempo")
    private int valorTiempo;
    @Column(name = "unidad_tiempo")
    private String unidadTiempo;
    
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "dosis", cascade = CascadeType.ALL)
    private Set<DosisAplicada> dosisAplicada = new HashSet<>();

    //private Set<Historial> historiales = new HashSet<>();

    public Dosis() {
    }

    public Dosis(int id, Vacuna vacuna, int valorTiempo, String unidadTiempo) {
        this.id = id;
        this.vacuna = vacuna;
        this.valorTiempo = valorTiempo;
        this.unidadTiempo = unidadTiempo;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Vacuna getVacuna() {
        return vacuna;
    }

    public void setVacuna(Vacuna vacuna) {
        this.vacuna = vacuna;
    }

    public int getValorTiempo() {
        return valorTiempo;
    }

    public void setValorTiempo(int valorTiempo) {
        this.valorTiempo = valorTiempo;
    }

    public String getUnidadTiempo() {
        return unidadTiempo;
    }

    public void setUnidadTiempo(String unidadTiempo) {
        this.unidadTiempo = unidadTiempo;
    }

    public Set<DosisAplicada> getDosisAplicada() {
        return dosisAplicada;
    }

    public void setDosisAplicada(Set<DosisAplicada> dosisAplicada) {
        this.dosisAplicada = dosisAplicada;
    }

    
    
}
