package modelo;
// Generated 26/09/2020 10:45:07 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vacuna generated by hbm2java
 */
@Entity
@Table(name = "vacuna")
public class Vacuna  implements java.io.Serializable {


    @Id
    @Column(name = "id")
    private Integer id;
    
    @Column(name = "nombre")
    private String nombre;
    
    @Column(name = "description")
    private String description;
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "vacuna")
    private Set<Dosis> dosises = new HashSet(0);
     
     //private Set<Enfermedad> enfermedades = new HashSet<>();
    
    @ManyToMany(cascade = {CascadeType.ALL})
    @JoinTable(name = "enfermedad_vacuna", joinColumns = {@JoinColumn(name = "id_vacuna")}, inverseJoinColumns = {@JoinColumn(name = "id_enfermedad")})
    private Set<Enfermedad> enfermedades = new HashSet<>();

    public Vacuna() {
    }

    public Vacuna(Integer id, String nombre, String description) {
        this.id = id;
        this.nombre = nombre;
        this.description = description;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set getDosises() {
        return dosises;
    }

    public void setDosises(Set dosises) {
        this.dosises = dosises;
    }

    public Set<Enfermedad> getEnfermedades() {
        return enfermedades;
    }

    public void setEnfermedades(Set<Enfermedad> enfermedades) {
        this.enfermedades = enfermedades;
    }
     
     
     



}


